Repository JamesPartsafas/soen390, pull requests merged in 2023-02, with the labels that each got.

#64 Allow report generation
  synapsis/pom.xml
Labels: bug

#71 #24 Connect with other users
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/Connection.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionKey.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionService.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionKeyTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionTest.java
Labels: user story

#73 #21 implement SSO login with Google, including associated tests
  synapsis/pom.xml
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AuthProvider.java
  synapsis/src/main/java/com/soen/synapsis/appuser/WebSecurityConfiguration.java
  synapsis/src/main/java/com/soen/synapsis/appuser/oauth/CustomOAuth2User.java
  synapsis/src/main/java/com/soen/synapsis/appuser/oauth/CustomOAuth2UserService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/registration/RegistrationService.java
  synapsis/src/main/java/com/soen/synapsis/utility/Constants.java
  synapsis/src/main/resources/application.properties
  synapsis/src/main/resources/data.sql
  synapsis/src/main/resources/templates/pages/login.html
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserDetailsServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/WebSecurityConfigurationTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/oauth/CustomOAuth2UserTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/registration/RegistrationServiceTest.java
  synapsis/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: backend

#77 #59 Company can mark candidates as recruiters
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserDetails.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserDetailsTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
Labels: backend

#81 #79-Create-DockerFile
  Dockerfile
Labels: devops

#83 #82 Generate javadocs on merge to main
  .github/workflows/generate-docs.yml
  synapsis/pom.xml
Labels: devops

#78 2.5 networking frontend
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/registration/RegistrationController.java
  synapsis/src/main/resources/static/css/styles.css
  synapsis/src/main/resources/templates/_layout.html
  synapsis/src/main/resources/templates/fragments/footer.html
  synapsis/src/main/resources/templates/fragments/navbar.html
  synapsis/src/main/resources/templates/pages/network.html
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/utilities/SecurityUtilities.java
Labels: frontend

#85 #25 View connections in Network page
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserDetails.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionService.java
  synapsis/src/main/resources/data.sql
  synapsis/src/main/resources/static/assets/default_user.svg
  synapsis/src/main/resources/templates/pages/network.html
  synapsis/src/test/java/com/soen/synapsis/integration/ConnectionRepositoryTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserDetailsTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionServiceTest.java
Labels: backend, frontend

#86 #69 Change Password Form
  synapsis/src/main/resources/static/js/changePassword.js
  synapsis/src/main/resources/templates/pages/passwordResetForm.html
Labels: frontend

#90 #26 view connection requests
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionService.java
  synapsis/src/main/resources/templates/pages/network.html
  synapsis/src/test/java/com/soen/synapsis/integration/ConnectionRepositoryTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionServiceTest.java
Labels: backend

#89 #22 customize and update the company and user profile
  .gitignore
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserDetails.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/appuserprofile/AppUserProfile.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/appuserprofile/AppUserProfileRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/appuserprofile/AppUserProfileService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/appuserprofile/updateprofile/UpdateAppUserProfileController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/appuserprofile/updateprofile/UpdateAppUserProfileRequest.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/appuserprofile/updateprofile/UpdateAppUserProfileService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/companyprofile/CompanyProfile.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/companyprofile/CompanyProfileRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/companyprofile/updateprofile/UpdateCompanyProfileController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/companyprofile/updateprofile/UpdateCompanyProfileRequest.java
  synapsis/src/main/java/com/soen/synapsis/appuser/profile/companyprofile/updateprofile/UpdateCompanyProfileService.java
  synapsis/src/main/resources/data.sql
  synapsis/src/main/resources/static/css/styles.css
  synapsis/src/main/resources/templates/fragments/footer.html
  synapsis/src/main/resources/templates/pages/companypage.html
  synapsis/src/main/resources/templates/pages/updatecompanypage.html
  synapsis/src/main/resources/templates/pages/updateuserpage.html
  synapsis/src/main/resources/templates/pages/userpage.html
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/appuserprofile/updateprofile/UpdateAppUserProfileRequestTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/companyprofile/updateprofile/UpdateCompanyProfileRequestTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/companyprofiletest/CompanyProfileTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/companyprofiletest/UpdateCompanyProfileControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/companyprofiletest/UpdateCompanyProfileRequestTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/companyprofiletest/UpdateCompanyProfileServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/userprofiletest/AppUserProfileTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/userprofiletest/UpdateAppUserProfileControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/userprofiletest/UpdateAppUserProfileRequestTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/profile/userprofiletest/UpdateAppUserProfileServiceTest.java
Labels: backend, frontend

#87 #68 Implemented homepage design based on mockup
  synapsis/src/main/resources/static/assets/hero1.png
  synapsis/src/main/resources/static/assets/hero2.png
  synapsis/src/main/resources/static/assets/hero3.png
  synapsis/src/main/resources/templates/fragments/footer.html
  synapsis/src/main/resources/templates/fragments/navbar.html
  synapsis/src/main/resources/templates/pages/home.html
Labels: frontend

#80 #50 create job posting
  synapsis/src/main/java/com/soen/synapsis/appuser/job/Job.java
  synapsis/src/main/java/com/soen/synapsis/appuser/job/JobController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/job/JobRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/job/JobRequest.java
  synapsis/src/main/java/com/soen/synapsis/appuser/job/JobService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/job/JobType.java
  synapsis/src/main/resources/data.sql
  synapsis/src/main/resources/templates/pages/createJob.html
  synapsis/src/main/resources/templates/pages/job.html
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/job/JobControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/job/JobRequestTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/job/JobServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/job/JobTest.java
Labels: backend

#84 #76 Implemented backend functions for a company to unmark a recruiter as a candidate
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserTest.java
Labels: backend

#93 #92 search users and companies
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/resources/templates/pages/network.html
  synapsis/src/main/resources/templates/pages/usersearchpage.html
  synapsis/src/test/java/com/soen/synapsis/integration/AppUserRepositoryTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
Labels: backend

#94 #27 disconnect from user
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/connection/ConnectionService.java
  synapsis/src/main/resources/templates/pages/companypage.html
  synapsis/src/main/resources/templates/pages/network.html
  synapsis/src/main/resources/templates/pages/userpage.html
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/connection/ConnectionServiceTest.java
Labels: backend

#96 Resolved misaligned elements
  synapsis/src/main/resources/templates/pages/companypage.html
  synapsis/src/main/resources/templates/pages/updatecompanypage.html
  synapsis/src/main/resources/templates/pages/updateuserpage.html
  synapsis/src/main/resources/templates/pages/userpage.html
Labels: bug, frontend

#97 #22 Added link and redirect logic to controller so that the authentic…
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/resources/templates/fragments/navbar.html
Labels: bug, frontend

#100 Fixed unlinked images in sign-in page.
  synapsis/src/main/resources/static/assets/synapsis_logo.svg
  synapsis/src/main/resources/templates/pages/login.html
Labels: bug, frontend
