Repository JamesPartsafas/soen390, pull requests merged in 2023-04, with the labels that each got.

#314 #312 Printing bug in Job Application page
  synapsis/src/main/java/com/soen/synapsis/appuser/job/JobController.java
  synapsis/src/main/resources/templates/pages/jobApplicationForm.html
Labels: bug

#315 #313 finished responsiveness of update company page
  synapsis/src/main/resources/templates/pages/updatecompanypage.html
Labels: frontend

#317 311 localization part3
  synapsis/src/main/resources/templates/pages/accessDenied.html
  synapsis/src/main/resources/templates/pages/adminCreationSuccess.html
  synapsis/src/main/resources/templates/pages/applicationSuccess.html
  synapsis/src/main/resources/templates/pages/chatPage.html
  synapsis/src/main/resources/templates/pages/companypage.html
  synapsis/src/main/resources/templates/pages/createJob.html
  synapsis/src/main/resources/templates/pages/editJob.html
  synapsis/src/main/resources/templates/pages/jobApplicationExternal.html
  synapsis/src/main/resources/templates/pages/jobApplicationForm.html
  synapsis/src/main/resources/templates/pages/jobs.html
  synapsis/src/main/resources/templates/pages/messagingPage.html
  synapsis/src/main/resources/templates/pages/network.html
  synapsis/src/main/resources/templates/pages/updatecompanypage.html
  synapsis/src/main/resources/templates/pages/updateuserpage.html
  synapsis/src/main/resources/templates/pages/userpage.html
  synapsis/src/main/resources/templates/pages/usersearchpage.html
Labels: frontend, refactor

#316 45 responsive design
  synapsis/src/main/resources/static/js/countries.js
  synapsis/src/main/resources/static/js/main.js
  synapsis/src/main/resources/templates/fragments/navbar.html
  synapsis/src/main/resources/templates/pages/applicationSuccess.html
  synapsis/src/main/resources/templates/pages/chatPage.html
  synapsis/src/main/resources/templates/pages/messagingPage.html
Labels: bug, frontend

#321 Fixed navbar bug.
  synapsis/src/main/resources/templates/fragments/navbar.html
Labels: bug

#326 Fixed responsiveness of chat page
  synapsis/src/main/resources/static/js/main.js
  synapsis/src/main/resources/templates/pages/chatPage.html
  synapsis/src/main/resources/templates/pages/messagingPage.html
Labels: bug

#325 #324 Admin footer fixed
  synapsis/src/main/resources/templates/pages/adminCreationSuccess.html
Labels: bug, frontend

#328 #323 finished localization bugs
  synapsis/src/main/resources/templates/pages/job.html
  synapsis/src/main/resources/templates/pages/savedjobs.html
  synapsis/src/main/resources/templates/pages/suggestedjobs.html
Labels: bug, frontend

#322 Fixed footer bug
  synapsis/src/main/resources/templates/fragments/footer.html
Labels: bug

#329 Fixed countries not loading and submitting
  synapsis/src/main/resources/templates/pages/updatecompanypage.html
Labels: bug

#331 #330 company page responsive fixed
  synapsis/src/main/resources/templates/pages/companypage.html
Labels: bug

#335 Fixed French chat bug
  synapsis/src/main/resources/static/js/main.js
  synapsis/src/main/resources/templates/pages/messagingPage.html
Labels: bug

#333 #332 my created jobs localized
  synapsis/src/main/resources/templates/pages/myJobs.html
  synapsis/src/main/resources/templates/pages/userpage.html
Labels: frontend

#338 Fixed countries bug in job application form
  synapsis/src/main/resources/templates/pages/jobApplicationForm.html
Labels: bug

#339 Register Page Bug
  synapsis/src/main/resources/templates/pages/register.html
Labels: bug

#340 336 chat styling bug
  synapsis/src/main/java/com/soen/synapsis/websockets/chat/ChatController.java
  synapsis/src/main/java/com/soen/synapsis/websockets/chat/message/Message.java
  synapsis/src/main/resources/static/js/FlowbiteUtils.js
  synapsis/src/main/resources/static/js/main.js
  synapsis/src/main/resources/templates/pages/messagingPage.html
Labels: bug

#342 #341 deletes all jobs associated to a company when the company is unm…
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/job/JobRepository.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
Labels: backend

#343 #341 added requested changes
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
Labels: backend
