Repository JamesPartsafas/soen390, pull requests merged in 2023-01, with the labels that each got.

#2 Create base template for project
  synapsis/.gitignore
  synapsis/.mvn/wrapper/maven-wrapper.jar
  synapsis/.mvn/wrapper/maven-wrapper.properties
  synapsis/mvnw
  synapsis/mvnw.cmd
  synapsis/pom.xml
  synapsis/src/main/java/com/soen/synapsis/SynapsisApplication.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/java/com/soen/synapsis/index/IndexController.java
  synapsis/src/main/java/com/soen/synapsis/index/IndexService.java
  synapsis/src/main/resources/application.properties
  synapsis/src/main/resources/static/css/styles.css
  synapsis/src/main/resources/static/js/index.js
  synapsis/src/main/resources/templates/_layout.html
  synapsis/src/main/resources/templates/fragments/footer.html
  synapsis/src/main/resources/templates/fragments/navbar.html
  synapsis/src/main/resources/templates/pages/home.html
  synapsis/src/test/java/com/soen/synapsis/SynapsisApplicationTests.java
Labels: backend, frontend

#5 Implement boilerplate for Spring Security
  synapsis/.gitignore
  synapsis/pom.xml
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUser.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserDetails.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserDetailsService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserRepository.java
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/Role.java
  synapsis/src/main/java/com/soen/synapsis/appuser/WebSecurityConfiguration.java
  synapsis/src/main/resources/application.properties
  synapsis/src/main/resources/data.sql
Labels: backend, database

#4 Added generic CSS for sitewide use
  synapsis/src/main/resources/static/css/styles.css
Labels: frontend

#8 Create tests for existing classes
  synapsis/pom.xml
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserDetails.java
  synapsis/src/main/java/com/soen/synapsis/appuser/WebSecurityConfiguration.java
  synapsis/src/main/java/com/soen/synapsis/index/IndexService.java
  synapsis/src/test/java/com/soen/synapsis/SynapsisApplicationTests.java
  synapsis/src/test/java/com/soen/synapsis/integration/AppUserRepositoryTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserDetailsServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserDetailsTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/WebSecurityConfigurationTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/index/IndexControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/index/IndexServiceTest.java
  synapsis/src/test/resources/application.properties
Labels: backend

#10 Updated the Readme File
  README.md
Labels: documentation

#12 Uploaded logo
  synapsis/src/main/resources/static/assets/synapsis_black.svg
  synapsis/src/main/resources/static/assets/synapsis_red.svg
  synapsis/src/main/resources/static/assets/synapsis_white.svg
Labels: frontend

#16 Updated Readme
  README.md
Labels: documentation

#18 Set users to candidate role by default
  synapsis/src/main/java/com/soen/synapsis/appuser/Role.java
  synapsis/src/main/java/com/soen/synapsis/appuser/WebSecurityConfiguration.java
  synapsis/src/main/java/com/soen/synapsis/appuser/registration/RegistrationService.java
  synapsis/src/main/resources/data.sql
  synapsis/src/test/java/com/soen/synapsis/integration/AppUserRepositoryTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserDetailsTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserTest.java
Labels: bug

#55 Styled navbar, footer, home and login page
  synapsis/pom.xml
  synapsis/src/main/java/com/soen/synapsis/index/IndexController.java
  synapsis/src/main/resources/static/assets/apple-logo.png
  synapsis/src/main/resources/static/assets/facebook-logo.png
  synapsis/src/main/resources/static/assets/google-logo.png
  synapsis/src/main/resources/static/css/styles.css
  synapsis/src/main/resources/templates/_layout.html
  synapsis/src/main/resources/templates/fragments/footer.html
  synapsis/src/main/resources/templates/fragments/navbar.html
  synapsis/src/main/resources/templates/pages/home.html
  synapsis/src/main/resources/templates/pages/login.html
Labels: frontend

#60 Allow users to register as either candidates or as companies
  synapsis/pom.xml
  synapsis/src/main/java/com/soen/synapsis/appuser/AppUserService.java
  synapsis/src/main/java/com/soen/synapsis/appuser/Role.java
  synapsis/src/main/java/com/soen/synapsis/appuser/WebSecurityConfiguration.java
  synapsis/src/main/java/com/soen/synapsis/appuser/registration/RegistrationController.java
  synapsis/src/main/java/com/soen/synapsis/appuser/registration/RegistrationRequest.java
  synapsis/src/main/java/com/soen/synapsis/appuser/registration/RegistrationService.java
  synapsis/src/main/java/com/soen/synapsis/utility/Constants.java
  synapsis/src/main/java/com/soen/synapsis/utility/ExcludeFromGeneratedTestReport.java
  synapsis/src/main/resources/data.sql
  synapsis/src/main/resources/templates/pages/register.html
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/AppUserServiceTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/registration/RegistrationControllerTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/registration/RegistrationRequestTest.java
  synapsis/src/test/java/com/soen/synapsis/unit/appuser/registration/RegistrationServiceTest.java
Labels: backend

#62 Automate test running
  .github/workflows/run-tests.yml
  synapsis/pom.xml
Labels: devops
